{{- if .Values.podMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "scanexporter.fullname" . }}
spec:
    namespaceSelector:
      matchNames:
      - apps
    podMetricsEndpoints:
      - interval: 10s
        scrapeTimeout: 10s
        port: metrics
        path: {{ .Values.podMonitor.path }}
    selector:
      matchLabels:
          app: {{ include "scanexporter.fullname" . }}
{{- end }}