scanexporter:
    name: scan-exporter
    replicaCount: 1
    liveness:
        period: 3
        path: /health
    container:
        image: devopsworks/scan-exporter:0.6.1
        port: 2112

redis:
    name: redis
    usePassword: false
    replicaCount: 1
    db: 0
    container:
        image: redis:latest
        port: 6379

nameOverride: ""
fullnameOverride: ""

podMonitor: 
    enabled: false
    path: /metrics

# Add targets to scan-exporter by uncommenting this section. 
# targets: |-
#         targets:       
#             - name: "app1"
#               ip: "128.66.0.1"
#               workers: 750
#               tcp:
#                 period: "10s"
#                 range: "reserved"
#                 expected: "53"

#             - name: "app2"
#               ip: "128.66.0.2"
#               workers: 1000
#               tcp:
#                 period: "1m"
#                 range: "all"
#                 expected: "22,443"
#               icmp:
#                 period: "30s"